name: geohashtree
description: GeohashTree is a tree implimentation to speed up spacial queries through geohash indexing.
version: 1.0.2
homepage: https://github.com/anovis/geohashtree

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  proximity_hash: ^1.0.1
  dart_geohash: ^1.0.2

dev_dependencies:
  test: ^1.2.0
