name: geohashtree
description: A new Flutter package project.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  proximity_hash: ^1.0.1

dev_dependencies:
  test: ^1.2.0
